# Generated by Django 5.0.7 on 2024-12-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='elected_positions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='election',
            name='election_for',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
