# Generated by Django 5.0.7 on 2024-12-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='election',
        ),
        migrations.RemoveField(
            model_name='election',
            name='elected_positions',
        ),
        migrations.AddField(
            model_name='election',
            name='elected_positions',
            field=models.ManyToManyField(blank=True, to='app.position'),
        ),
    ]
